### PR TITLE
Deps upgrade with sdk

### PR DESCRIPTION
**Pull request by JEuler**

### CODE REVIEW

**Comment by davidAg9** [comment]
please if possible push these changes quickly because its conflicting with some of our upgraded dependencies

**Comment by dorsamet** [comment]
@JEuler is this planned on being pushed in?

**Comment by JEuler** [comment]
> @JEuler is this planned on being pushed in?

 But it is not on me.

**Comment by EdwynZN** [comment]
i don't what to think the project is abandoned but for now your fork is the most updated so I will use it to keep upgrading my other packages, great job!

**Comment by JEuler** [comment]
Have a look at https://pub.dev/packages/flutter_dotenv, I have switched from envify due to no updates situation :(

**Comment by EdwynZN** [comment]
Thank you, I read about that package before envify but I didn't like the idea of using assets to save .env files (also the const attributes were a plus from envify). Have you experience any regression by using dotenv?

I'm also using --dart-define in other projects with CICD and I find it really simple and useful, but of course it's a long command the more parameters I have and sometimes when working with groups of people an env file is better

**Comment by frencojobs** [comment]
Hey guys, sorry for the trouble. Life kept getting in the way and only from last week that I started working on open-source again. I've just discussed with the maintainers of [Envied](https://github.com/petercinibulk/envied) and I'll be deprecating Envify in favor of it.

Envify is fixed so it's no longer unusable but that'll be the final update. After that it'll no longer receive further updates and will be discontinued soon. So, I'd suggest you to migrate to it if you're still using Envify. I'll be closing this PR since SDK and dependencies are now updated.

Thank you for the PR @JEuler and have a good day everyone!

**Pull request closed without merging**
