### PR TITLE
Null value support

### PR DESCRIPTION
**Pull request by debkanchan**
This adds support for Nullable types. If a key is nullable, envify won't throw an error if it can't find the value in `.env`.

This can be considered a BREAKING change since `dynamic` is by syntactical definition nullable so the existing `dynamic` values will no longer throw an error if there's no corresponding value in `.env`.

It also no longer throws `Environment variables file doesn't exist at .env.` error instead just warns the user about it. If any field is not nullable AND `.env` file is not present / not in `.env` file it then throws an `Environment variable not found for field foo.` error.

### CODE REVIEW

**Comment by DebkanchanSamadder** [comment]
@frencojobs

**Comment by DebkanchanSamadder** [comment]
@frencojobs

**Comment by lordvidex** [comment]
You can add this null value support to the [`envied`](https://github.com/petercinibulk/envied) package which is active and actually built upon `envify`

**Comment by frencojobs** [comment]
Sorry for the trouble. I was unresponsive for a while. I just got back and I've decided to deprecate Envify in favor of [Envied](https://github.com/petercinibulk/envied) after discussing with it's maintainers. Please feel free to try it and open a PR there if you still want this feature. Envify will no longer receive updates and I'm closing this PR.

Thank you for your interest and have a good day!

**Pull request closed without merging**
